version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: currency-postgres
    environment:
      POSTGRES_DB: currencydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"