spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/currencydb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 600000

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  exchange:
    api-url: https://openexchangerates.org/api/latest.json
    app-id: YOUR_APP_ID_HERE